version: "3"
services:
  etcd:
    #build: .
    image: chenglongcl/etcd:v3.4.9
    container_name: etcd-3.4.9-container
    hostname: etcd
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - custom
    environment:
      ETCDCTL_API: 3
    volumes:
      - ~/dockerMaps/data/etcd-3.4.9:/etcd-data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    command:
      - "/usr/local/bin/etcd"
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - --listen-client-urls
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-state"
      - "new"
      - "--log-level"
      - "info"
      - "--logger"
      - "zap"
      - "--log-outputs"
      - "stderr"
networks:
  custom:
    external: true
