version: "3"
services:
  kibana:
    image: kibana:7.10.1
    container_name: kibana-7.10.1-container
    hostname: kibana
    ports:
      - 5601:5601
    networks:
      - custom
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOST: 0.0.0.0
      I18N_LOCALE: zh-CN
      TZ: Asia/Shanghai
    volumes:
      - ~/dockerMaps/conf/kibana-7.10.1/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always
networks:
  custom:
    external: true