version: "3"
services:
  mysql:
    image: mysql:5.7.21
    container_name: mysql-5.7.21-container
    hostname: mysql
    ports:
      - "3306:3306"
    networks:
      - custom
    environment:
      MYSQL_ROOT_PASSWORD: 20190604
      TZ: Asia/Shanghai
    volumes:
      - ~/dockerMaps/data/mysql5.7.21:/var/lib/mysql
      - ~/dockerMaps/conf/mysql5.7.21/conf.d:/etc/mysql/conf.d
      - ~/dockerMaps/logs/mysql5.7.21:/logs
    restart: always
  redis:
    image: redis:3.2.12
    container_name: redis-3.2.12-container
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - custom
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ~/dockerMaps/data/redis3.2.12:/data
    command: redis-server --appendonly yes --requirepass "20190604"
    restart: always
  nginx:
    image: nginx:1.15.12
    container_name: nginx-1.15.12-container
    ports:
      - "80:80"
      - "443:443"
    networks:
      - custom
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ~/webroot:/webroot
      - ~/dockerMaps/conf/nginx1.15.12/nginx.conf:/etc/nginx/nginx.conf
      - ~/dockerMaps/conf/nginx1.15.12/conf.d:/etc/nginx/conf.d
      - ~/dockerMaps/logs/nginx1.15.12:/var/log/nginx
      - ~/dockerMaps/other/nginx1.15.12/ssl:/ssl
    command: nginx -g 'daemon off;'
    restart: always
networks:
  custom:
    external: true
